### ISSUE TITLE
blacklist the locations that aren't actual lookout towers/cabins

### ISSUE THREAD

**Issue by gerirosenberg** [mileswwatkins/lookout_hunter#30]

**Comment by mileswwatkins** [comment]
Will be reflected in live data following the next production scrape

<img width="570" alt="Screen Shot 2023-02-26 at 13 59 12" src="https://user-images.githubusercontent.com/4959135/221439955-4d76ff3f-0ff0-4b33-93e9-71fa280080bf.png">
